@echo off

::
:: Copyright 2015 the original authors.
::
:: Licensed under the Apache License, Version 2.0 (the "License");
:: you may not use this file except in compliance with the License.
:: You may obtain a copy of the License at
::
::      https://www.apache.org/licenses/LICENSE-2.0
::
:: Unless required by applicable law or agreed to in writing, software
:: distributed under the License is distributed on an "AS IS" BASIS,
:: WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
:: See the License for the specific language governing permissions and
:: limitations under the License.
::

@rem ##########################################################################
@rem ##
@rem ##  Gradle startup script for Windows generated by Gradle.
@rem ##
@rem ##########################################################################

@if "%DEBUG%"=="" @echo off
@setlocal

set DIRNAME=%~dp0
if "%DIRNAME%"=="" set DIRNAME=.
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%

@rem Resolve any "." and ".." in APP_HOME to make it shorter.
for %%i in ("%APP_HOME%") do set APP_HOME=%%~fi

@rem Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
set DEFAULT_JVM_OPTS=-Xmx64m -Xms64m

set CLASSPATH=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar
for %%G in (
    gradle-base-annotations-8.7.jar
    gradle-cli-8.7.jar
    gradle-files-8.7.jar
    gradle-functional-8.7.jar
    gradle-wrapper-shared-8.7.jar
) do (
    if exist "%APP_HOME%\gradle\wrapper\%%G" set CLASSPATH=%CLASSPATH%;%APP_HOME%\gradle\wrapper\%%G
)

@if exist "%JAVA_HOME%" goto findJavaFromJavaHome

set JAVA_EXE=java.exe
%JAVA_EXE% -version >NUL 2>&1
if %ERRORLEVEL% equ 0 goto execute

echo.
echo ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
echo.
echo Please set the JAVA_HOME variable in your environment to match the
 echo location of your Java installation.
goto fail

:findJavaFromJavaHome
set JAVA_HOME=%JAVA_HOME:"=%
set JAVA_EXE=%JAVA_HOME%\bin\java.exe

if exist "%JAVA_EXE%" goto execute

echo.
echo ERROR: JAVA_HOME is set to an invalid directory: %JAVA_HOME%
echo.
echo Please set the JAVA_HOME variable in your environment to match the
 echo location of your Java installation.
goto fail

:execute
set CMD_LINE_ARGS=
set _SKIP=2

:parseArgs
if "%~1"=="" goto endParseArgs

set ARG=%~1
set CMD_LINE_ARGS=%CMD_LINE_ARGS% %ARG%
shift
if "%~1"=="" goto endParseArgs
set ARG=%~1
if "%ARG:~0,1%"==""" set ARG=%ARG:~1,-1%
set CMD_LINE_ARGS=%CMD_LINE_ARGS% "%ARG%"
shift
goto parseArgs

:endParseArgs

"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %CMD_LINE_ARGS%
goto end

:fail
set EXIT_CODE=%ERRORLEVEL%
if %EXIT_CODE% equ 0 set EXIT_CODE=1
exit /b %EXIT_CODE%

:end
if "%OS%"=="Windows_NT" endlocal

:omega
